services:
  - type: web
    name: indicator-alert
    runtime: node
    repo: https://github.com/jrin0/mts
    plan: free
    envVars:
  - key: NODE_ENV
    sync: false
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    autoDeployTrigger: commit
version: "1"
